languageCode: en-us
baseURL: "https://andTEJAsan.github.io"
title: Tejas Anand
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Tejas Anand
  description: "I Like Programming For fun"
  keywords: [Blog, Portfolio, Data Science]
  author: Tejas Anand
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Tejas Anand"
    icon: "img/coding.png"
    iconHeight: 35
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome! \U0001F44B"
    subtitle: "Fun for Programming. If you wish to truly understand something, try to look at it from all directions. It never harms to listen to whatever anyone has to say about anything."
    imageUrl: "img/fp.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Data Professor"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: ""

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/tejasan/"
    - name: github
      url: "https://github.com/andTEJAsan"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
#     - identifier: infographics
#       name: Infographics
#       url: /infographics/
#       weight: 3
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai